name: Continuous Deployment Live

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SSH Create web API folder
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.REMOTE_TARGET_HOME }}
            rm -rf ./api
            mkdir -p ./api
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
      - name: SSH transfer API in server folder
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET_HOME }}/api
      - name: SSH Copy API to web folder & create Uploads folder & Install dependencies
        uses: fifsky/ssh-action@master
        with:
          command: |
            mkdir -p ${{ secrets.REMOTE_TARGET_WWW }}/api/
            cd ${{ secrets.REMOTE_TARGET_WWW }}/api/
            php7.4 artisan down
            rm -r ${{ secrets.REMOTE_TARGET_WWW }}/api/database/migrations/*
            cp ${{ secrets.REMOTE_TARGET_HOME }}/.env.api ${{ secrets.REMOTE_TARGET_HOME }}/api/.env
            cp -r ${{ secrets.REMOTE_TARGET_HOME }}/api/* ./
            php7.4 /usr/local/bin/composer install 
            php7.4 artisan migrate
            php7.4 artisan cache:clear
            php7.4 artisan queue:restart
            php7.4 artisan up
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #     steps:
  #         - uses: actions/checkout@v2
  #         - name: Laravel Setup
  #           run: |
  #             cp .env.ci .env
  #             composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
  #             php artisan key:generate
  #             chmod -R 777 storage bootstrap/cache
  #         - name: Execute tests (Unit and Feature tests) via PHPUnit
  #           env:
  #             DB_CONNECTION: mysql
  #             DB_DATABASE: db_test
  #             DB_PORT: 33306
  #             DB_USER: root
  #             DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #           run: |
  #             php artisan migrate
  #             vendor/phpunit/phpunit/phpunit
  # deploy:
  #   needs: test
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v2
  #       - name: Laravel Deploy
